// Code generated by MockGen. DO NOT EDIT.
// Source: internal/ctls/aescipher/aescipher.go
//
// Generated by this command:
//
//	mockgen -source=internal/ctls/aescipher/aescipher.go -destination=test/mocks/mock_aescipher/mock_aescipher.go -package=mock_aescipher
//

// Package mock_aescipher is a generated GoMock package.
package mock_aescipher

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCipherer is a mock of Cipherer interface.
type MockCipherer struct {
	ctrl     *gomock.Controller
	recorder *MockCiphererMockRecorder
	isgomock struct{}
}

// MockCiphererMockRecorder is the mock recorder for MockCipherer.
type MockCiphererMockRecorder struct {
	mock *MockCipherer
}

// NewMockCipherer creates a new mock instance.
func NewMockCipherer(ctrl *gomock.Controller) *MockCipherer {
	mock := &MockCipherer{ctrl: ctrl}
	mock.recorder = &MockCiphererMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCipherer) EXPECT() *MockCiphererMockRecorder {
	return m.recorder
}

// Decrypt mocks base method.
func (m *MockCipherer) Decrypt(token string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decrypt", token)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decrypt indicates an expected call of Decrypt.
func (mr *MockCiphererMockRecorder) Decrypt(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decrypt", reflect.TypeOf((*MockCipherer)(nil).Decrypt), token)
}

// DecryptAndCompare mocks base method.
func (m *MockCipherer) DecryptAndCompare(token, other string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecryptAndCompare", token, other)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecryptAndCompare indicates an expected call of DecryptAndCompare.
func (mr *MockCiphererMockRecorder) DecryptAndCompare(token, other any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecryptAndCompare", reflect.TypeOf((*MockCipherer)(nil).DecryptAndCompare), token, other)
}

// Encrypt mocks base method.
func (m *MockCipherer) Encrypt(plain string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encrypt", plain)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Encrypt indicates an expected call of Encrypt.
func (mr *MockCiphererMockRecorder) Encrypt(plain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encrypt", reflect.TypeOf((*MockCipherer)(nil).Encrypt), plain)
}
