// Code generated by MockGen. DO NOT EDIT.
// Source: internal/ctls/logs/logs.go
//
// Generated by this command:
//
//	mockgen -source=internal/ctls/logs/logs.go -destination=test/mocks/mock_logs/mock_logs.go -package=mock_logs
//

// Package mock_logs is a generated GoMock package.
package mock_logs

import (
	context "context"
	slog "log/slog"
	reflect "reflect"

	logs "github.com/llnl/wormhole-holepunch/internal/ctls/logs"
	gomock "go.uber.org/mock/gomock"
)

// MockLogger is a mock of Logger interface.
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
	isgomock struct{}
}

// MockLoggerMockRecorder is the mock recorder for MockLogger.
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance.
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// Debug mocks base method.
func (m *MockLogger) Debug(msg string, attr ...slog.Attr) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range attr {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Debug", varargs...)
}

// Debug indicates an expected call of Debug.
func (mr *MockLoggerMockRecorder) Debug(msg any, attr ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, attr...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debug", reflect.TypeOf((*MockLogger)(nil).Debug), varargs...)
}

// DebugCtx mocks base method.
func (m *MockLogger) DebugCtx(ctx context.Context, msg string, attr ...slog.Attr) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, msg}
	for _, a := range attr {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "DebugCtx", varargs...)
}

// DebugCtx indicates an expected call of DebugCtx.
func (mr *MockLoggerMockRecorder) DebugCtx(ctx, msg any, attr ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, msg}, attr...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DebugCtx", reflect.TypeOf((*MockLogger)(nil).DebugCtx), varargs...)
}

// Debugf mocks base method.
func (m *MockLogger) Debugf(format string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Debugf", varargs...)
}

// Debugf indicates an expected call of Debugf.
func (mr *MockLoggerMockRecorder) Debugf(format any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{format}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debugf", reflect.TypeOf((*MockLogger)(nil).Debugf), varargs...)
}

// Error mocks base method.
func (m *MockLogger) Error(msg string, attr ...slog.Attr) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range attr {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Error", varargs...)
}

// Error indicates an expected call of Error.
func (mr *MockLoggerMockRecorder) Error(msg any, attr ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, attr...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockLogger)(nil).Error), varargs...)
}

// ErrorCtx mocks base method.
func (m *MockLogger) ErrorCtx(ctx context.Context, msg string, attr ...slog.Attr) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, msg}
	for _, a := range attr {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "ErrorCtx", varargs...)
}

// ErrorCtx indicates an expected call of ErrorCtx.
func (mr *MockLoggerMockRecorder) ErrorCtx(ctx, msg any, attr ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, msg}, attr...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ErrorCtx", reflect.TypeOf((*MockLogger)(nil).ErrorCtx), varargs...)
}

// Errorf mocks base method.
func (m *MockLogger) Errorf(format string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Errorf", varargs...)
}

// Errorf indicates an expected call of Errorf.
func (mr *MockLoggerMockRecorder) Errorf(format any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{format}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Errorf", reflect.TypeOf((*MockLogger)(nil).Errorf), varargs...)
}

// Info mocks base method.
func (m *MockLogger) Info(msg string, attr ...slog.Attr) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range attr {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Info", varargs...)
}

// Info indicates an expected call of Info.
func (mr *MockLoggerMockRecorder) Info(msg any, attr ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, attr...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockLogger)(nil).Info), varargs...)
}

// InfoCtx mocks base method.
func (m *MockLogger) InfoCtx(ctx context.Context, msg string, attr ...slog.Attr) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, msg}
	for _, a := range attr {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "InfoCtx", varargs...)
}

// InfoCtx indicates an expected call of InfoCtx.
func (mr *MockLoggerMockRecorder) InfoCtx(ctx, msg any, attr ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, msg}, attr...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InfoCtx", reflect.TypeOf((*MockLogger)(nil).InfoCtx), varargs...)
}

// Infof mocks base method.
func (m *MockLogger) Infof(format string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Infof", varargs...)
}

// Infof indicates an expected call of Infof.
func (mr *MockLoggerMockRecorder) Infof(format any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{format}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Infof", reflect.TypeOf((*MockLogger)(nil).Infof), varargs...)
}

// IntArg mocks base method.
func (m *MockLogger) IntArg(k string, v int) slog.Attr {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IntArg", k, v)
	ret0, _ := ret[0].(slog.Attr)
	return ret0
}

// IntArg indicates an expected call of IntArg.
func (mr *MockLoggerMockRecorder) IntArg(k, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IntArg", reflect.TypeOf((*MockLogger)(nil).IntArg), k, v)
}

// StartSpan mocks base method.
func (m *MockLogger) StartSpan(ctx context.Context, name string) (context.Context, func()) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartSpan", ctx, name)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(func())
	return ret0, ret1
}

// StartSpan indicates an expected call of StartSpan.
func (mr *MockLoggerMockRecorder) StartSpan(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartSpan", reflect.TypeOf((*MockLogger)(nil).StartSpan), ctx, name)
}

// StringArg mocks base method.
func (m *MockLogger) StringArg(k, v string) slog.Attr {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StringArg", k, v)
	ret0, _ := ret[0].(slog.Attr)
	return ret0
}

// StringArg indicates an expected call of StringArg.
func (mr *MockLoggerMockRecorder) StringArg(k, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StringArg", reflect.TypeOf((*MockLogger)(nil).StringArg), k, v)
}

// Warn mocks base method.
func (m *MockLogger) Warn(msg string, attr ...slog.Attr) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range attr {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Warn", varargs...)
}

// Warn indicates an expected call of Warn.
func (mr *MockLoggerMockRecorder) Warn(msg any, attr ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, attr...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warn", reflect.TypeOf((*MockLogger)(nil).Warn), varargs...)
}

// WarnCtx mocks base method.
func (m *MockLogger) WarnCtx(ctx context.Context, msg string, attr ...slog.Attr) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, msg}
	for _, a := range attr {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "WarnCtx", varargs...)
}

// WarnCtx indicates an expected call of WarnCtx.
func (mr *MockLoggerMockRecorder) WarnCtx(ctx, msg any, attr ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, msg}, attr...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WarnCtx", reflect.TypeOf((*MockLogger)(nil).WarnCtx), varargs...)
}

// Warnf mocks base method.
func (m *MockLogger) Warnf(format string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Warnf", varargs...)
}

// Warnf indicates an expected call of Warnf.
func (mr *MockLoggerMockRecorder) Warnf(format any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{format}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warnf", reflect.TypeOf((*MockLogger)(nil).Warnf), varargs...)
}

// With mocks base method.
func (m *MockLogger) With(attrs []slog.Attr) logs.Logger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "With", attrs)
	ret0, _ := ret[0].(logs.Logger)
	return ret0
}

// With indicates an expected call of With.
func (mr *MockLoggerMockRecorder) With(attrs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "With", reflect.TypeOf((*MockLogger)(nil).With), attrs)
}
