// Code generated by MockGen. DO NOT EDIT.
// Source: internal/wormhole/token/token.go
//
// Generated by this command:
//
//	mockgen -source=internal/wormhole/token/token.go -destination=test/mocks/mock_token/mock_token.go -package=mock_token
//

// Package mock_token is a generated GoMock package.
package mock_token

import (
	context "context"
	reflect "reflect"

	errs "github.com/llnl/wormhole-holepunch/internal/ctls/errs"
	logs "github.com/llnl/wormhole-holepunch/internal/ctls/logs"
	requests "github.com/llnl/wormhole-holepunch/internal/ctls/requests"
	wormhole "github.com/llnl/wormhole-holepunch/internal/wormhole"
	token "github.com/llnl/wormhole-holepunch/internal/wormhole/token"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthenticator is a mock of Authenticator interface.
type MockAuthenticator struct {
	ctrl     *gomock.Controller
	recorder *MockAuthenticatorMockRecorder
	isgomock struct{}
}

// MockAuthenticatorMockRecorder is the mock recorder for MockAuthenticator.
type MockAuthenticatorMockRecorder struct {
	mock *MockAuthenticator
}

// NewMockAuthenticator creates a new mock instance.
func NewMockAuthenticator(ctrl *gomock.Controller) *MockAuthenticator {
	mock := &MockAuthenticator{ctrl: ctrl}
	mock.recorder = &MockAuthenticatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthenticator) EXPECT() *MockAuthenticatorMockRecorder {
	return m.recorder
}

// InvalidateToken mocks base method.
func (m *MockAuthenticator) InvalidateToken(ctx context.Context, tokenID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InvalidateToken", ctx, tokenID)
}

// InvalidateToken indicates an expected call of InvalidateToken.
func (mr *MockAuthenticatorMockRecorder) InvalidateToken(ctx, tokenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateToken", reflect.TypeOf((*MockAuthenticator)(nil).InvalidateToken), ctx, tokenID)
}

// RemoveSubtoken mocks base method.
func (m *MockAuthenticator) RemoveSubtoken(ctx context.Context, parentID, externalID, tokenID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveSubtoken", ctx, parentID, externalID, tokenID)
}

// RemoveSubtoken indicates an expected call of RemoveSubtoken.
func (mr *MockAuthenticatorMockRecorder) RemoveSubtoken(ctx, parentID, externalID, tokenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveSubtoken", reflect.TypeOf((*MockAuthenticator)(nil).RemoveSubtoken), ctx, parentID, externalID, tokenID)
}

// RequestHeader mocks base method.
func (m *MockAuthenticator) RequestHeader(ctx context.Context, ll logs.Logger, req requests.RequestDetails) (wormhole.TokenContext, token.AuthResponse, *errs.StatusError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestHeader", ctx, ll, req)
	ret0, _ := ret[0].(wormhole.TokenContext)
	ret1, _ := ret[1].(token.AuthResponse)
	ret2, _ := ret[2].(*errs.StatusError)
	return ret0, ret1, ret2
}

// RequestHeader indicates an expected call of RequestHeader.
func (mr *MockAuthenticatorMockRecorder) RequestHeader(ctx, ll, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestHeader", reflect.TypeOf((*MockAuthenticator)(nil).RequestHeader), ctx, ll, req)
}

// SubtokenFlow mocks base method.
func (m *MockAuthenticator) SubtokenFlow(ctx context.Context, ll logs.Logger, req requests.RequestDetails, tknCtx wormhole.TokenContext) (string, *errs.StatusError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubtokenFlow", ctx, ll, req, tknCtx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*errs.StatusError)
	return ret0, ret1
}

// SubtokenFlow indicates an expected call of SubtokenFlow.
func (mr *MockAuthenticatorMockRecorder) SubtokenFlow(ctx, ll, req, tknCtx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubtokenFlow", reflect.TypeOf((*MockAuthenticator)(nil).SubtokenFlow), ctx, ll, req, tknCtx)
}
