// Code generated by MockGen. DO NOT EDIT.
// Source: internal/ctls/streams/kvstore.go
//
// Generated by this command:
//
//	mockgen -source=internal/ctls/streams/kvstore.go -destination=test/mocks/mock_streams/mock_kvstore.go -package=mock_streams
//

// Package mock_streams is a generated GoMock package.
package mock_streams

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockKVStore is a mock of KVStore interface.
type MockKVStore struct {
	ctrl     *gomock.Controller
	recorder *MockKVStoreMockRecorder
	isgomock struct{}
}

// MockKVStoreMockRecorder is the mock recorder for MockKVStore.
type MockKVStoreMockRecorder struct {
	mock *MockKVStore
}

// NewMockKVStore creates a new mock instance.
func NewMockKVStore(ctrl *gomock.Controller) *MockKVStore {
	mock := &MockKVStore{ctrl: ctrl}
	mock.recorder = &MockKVStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKVStore) EXPECT() *MockKVStoreMockRecorder {
	return m.recorder
}

// AllKeys mocks base method.
func (m *MockKVStore) AllKeys(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllKeys", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AllKeys indicates an expected call of AllKeys.
func (mr *MockKVStoreMockRecorder) AllKeys(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllKeys", reflect.TypeOf((*MockKVStore)(nil).AllKeys), ctx)
}

// Delete mocks base method.
func (m *MockKVStore) Delete(ctx context.Context, k string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, k)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockKVStoreMockRecorder) Delete(ctx, k any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockKVStore)(nil).Delete), ctx, k)
}

// Get mocks base method.
func (m *MockKVStore) Get(ctx context.Context, k string, v any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, k, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockKVStoreMockRecorder) Get(ctx, k, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockKVStore)(nil).Get), ctx, k, v)
}

// Put mocks base method.
func (m *MockKVStore) Put(ctx context.Context, k string, v any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, k, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *MockKVStoreMockRecorder) Put(ctx, k, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockKVStore)(nil).Put), ctx, k, v)
}
