// Code generated by MockGen. DO NOT EDIT.
// Source: internal/ctls/streams/pubsub.go
//
// Generated by this command:
//
//	mockgen -source=internal/ctls/streams/pubsub.go -destination=test/mocks/mock_streams/mock_pubsub.go -package=mock_streams
//

// Package mock_streams is a generated GoMock package.
package mock_streams

import (
	context "context"
	reflect "reflect"

	jetstream "github.com/nats-io/nats.go/jetstream"
	gomock "go.uber.org/mock/gomock"
)

// MockPubSub is a mock of PubSub interface.
type MockPubSub struct {
	ctrl     *gomock.Controller
	recorder *MockPubSubMockRecorder
	isgomock struct{}
}

// MockPubSubMockRecorder is the mock recorder for MockPubSub.
type MockPubSubMockRecorder struct {
	mock *MockPubSub
}

// NewMockPubSub creates a new mock instance.
func NewMockPubSub(ctrl *gomock.Controller) *MockPubSub {
	mock := &MockPubSub{ctrl: ctrl}
	mock.recorder = &MockPubSubMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPubSub) EXPECT() *MockPubSubMockRecorder {
	return m.recorder
}

// Consume mocks base method.
func (m *MockPubSub) Consume(ctx context.Context, handler jetstream.MessageHandler) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Consume", ctx, handler)
	ret0, _ := ret[0].(error)
	return ret0
}

// Consume indicates an expected call of Consume.
func (mr *MockPubSubMockRecorder) Consume(ctx, handler any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consume", reflect.TypeOf((*MockPubSub)(nil).Consume), ctx, handler)
}

// Publish mocks base method.
func (m *MockPubSub) Publish(ctx context.Context, v any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockPubSubMockRecorder) Publish(ctx, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockPubSub)(nil).Publish), ctx, v)
}

// PublishSingleMsg mocks base method.
func (m *MockPubSub) PublishSingleMsg(ctx context.Context, v any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishSingleMsg", ctx, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishSingleMsg indicates an expected call of PublishSingleMsg.
func (mr *MockPubSubMockRecorder) PublishSingleMsg(ctx, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishSingleMsg", reflect.TypeOf((*MockPubSub)(nil).PublishSingleMsg), ctx, v)
}
