// Code generated by MockGen. DO NOT EDIT.
// Source: internal/ctls/streams/kvstore.go
//
// Generated by this command:
//
//	mockgen -source=internal/ctls/streams/kvstore.go -destination=test/mocks/mock_streams/mock_kvstore.go -package=mock_streams
//

// Package mock_streams is a generated GoMock package.
package mock_streams

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockKVStore is a mock of KVStore interface.
type MockKVStore struct {
	ctrl     *gomock.Controller
	recorder *MockKVStoreMockRecorder
	isgomock struct{}
}

// MockKVStoreMockRecorder is the mock recorder for MockKVStore.
type MockKVStoreMockRecorder struct {
	mock *MockKVStore
}

// NewMockKVStore creates a new mock instance.
func NewMockKVStore(ctrl *gomock.Controller) *MockKVStore {
	mock := &MockKVStore{ctrl: ctrl}
	mock.recorder = &MockKVStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKVStore) EXPECT() *MockKVStoreMockRecorder {
	return m.recorder
}

// AllKeys mocks base method.
func (m *MockKVStore) AllKeys(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllKeys", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AllKeys indicates an expected call of AllKeys.
func (mr *MockKVStoreMockRecorder) AllKeys(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllKeys", reflect.TypeOf((*MockKVStore)(nil).AllKeys), ctx)
}

// Delete mocks base method.
func (m *MockKVStore) Delete(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockKVStoreMockRecorder) Delete(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockKVStore)(nil).Delete), ctx, key)
}

// Get mocks base method.
func (m *MockKVStore) Get(ctx context.Context, key string, val any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key, val)
	ret0, _ := ret[0].(error)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockKVStoreMockRecorder) Get(ctx, key, val any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockKVStore)(nil).Get), ctx, key, val)
}

// GetWithRevision mocks base method.
func (m *MockKVStore) GetWithRevision(ctx context.Context, key string, val any) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithRevision", ctx, key, val)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithRevision indicates an expected call of GetWithRevision.
func (mr *MockKVStoreMockRecorder) GetWithRevision(ctx, key, val any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithRevision", reflect.TypeOf((*MockKVStore)(nil).GetWithRevision), ctx, key, val)
}

// Put mocks base method.
func (m *MockKVStore) Put(ctx context.Context, key string, val any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, key, val)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *MockKVStoreMockRecorder) Put(ctx, key, val any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockKVStore)(nil).Put), ctx, key, val)
}

// UpdateWithRevision mocks base method.
func (m *MockKVStore) UpdateWithRevision(ctx context.Context, key string, val any, revision uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWithRevision", ctx, key, val, revision)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWithRevision indicates an expected call of UpdateWithRevision.
func (mr *MockKVStoreMockRecorder) UpdateWithRevision(ctx, key, val, revision any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWithRevision", reflect.TypeOf((*MockKVStore)(nil).UpdateWithRevision), ctx, key, val, revision)
}
