// Code generated by MockGen. DO NOT EDIT.
// Source: internal/oauthmngr/manager.go
//
// Generated by this command:
//
//	mockgen -source=internal/oauthmngr/manager.go -destination=test/mocks/mock_oauthmngr/mock_oauthmngr.go -package=mock_oauthmngr
//

// Package mock_oauthmngr is a generated GoMock package.
package mock_oauthmngr

import (
	context "context"
	http "net/http"
	reflect "reflect"

	errs "github.com/llnl/wormhole-holepunch/internal/ctls/errs"
	requests "github.com/llnl/wormhole-holepunch/internal/ctls/requests"
	oauthmngr "github.com/llnl/wormhole-holepunch/internal/oauthmngr"
	wormhole "github.com/llnl/wormhole-holepunch/internal/wormhole"
	gomock "go.uber.org/mock/gomock"
)

// MockValidator is a mock of Validator interface.
type MockValidator struct {
	ctrl     *gomock.Controller
	recorder *MockValidatorMockRecorder
	isgomock struct{}
}

// MockValidatorMockRecorder is the mock recorder for MockValidator.
type MockValidatorMockRecorder struct {
	mock *MockValidator
}

// NewMockValidator creates a new mock instance.
func NewMockValidator(ctrl *gomock.Controller) *MockValidator {
	mock := &MockValidator{ctrl: ctrl}
	mock.recorder = &MockValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidator) EXPECT() *MockValidatorMockRecorder {
	return m.recorder
}

// EstablishPreAuthFunc mocks base method.
func (m *MockValidator) EstablishPreAuthFunc(source wormhole.RawSource) func(requests.RequestDetails) (bool, *errs.StatusError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EstablishPreAuthFunc", source)
	ret0, _ := ret[0].(func(requests.RequestDetails) (bool, *errs.StatusError))
	return ret0
}

// EstablishPreAuthFunc indicates an expected call of EstablishPreAuthFunc.
func (mr *MockValidatorMockRecorder) EstablishPreAuthFunc(source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EstablishPreAuthFunc", reflect.TypeOf((*MockValidator)(nil).EstablishPreAuthFunc), source)
}

// ExpandSources mocks base method.
func (m *MockValidator) ExpandSources(rawSources []wormhole.RawSource) []wormhole.RawSource {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExpandSources", rawSources)
	ret0, _ := ret[0].([]wormhole.RawSource)
	return ret0
}

// ExpandSources indicates an expected call of ExpandSources.
func (mr *MockValidatorMockRecorder) ExpandSources(rawSources any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExpandSources", reflect.TypeOf((*MockValidator)(nil).ExpandSources), rawSources)
}

// PrepareAuthRedirect mocks base method.
func (m *MockValidator) PrepareAuthRedirect(proposedRedirect string, details requests.RequestDetails) (string, *errs.StatusError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrepareAuthRedirect", proposedRedirect, details)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*errs.StatusError)
	return ret0, ret1
}

// PrepareAuthRedirect indicates an expected call of PrepareAuthRedirect.
func (mr *MockValidatorMockRecorder) PrepareAuthRedirect(proposedRedirect, details any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrepareAuthRedirect", reflect.TypeOf((*MockValidator)(nil).PrepareAuthRedirect), proposedRedirect, details)
}

// RedirectHandler mocks base method.
func (m *MockValidator) RedirectHandler(ctx context.Context, details requests.RequestDetails) (*http.Cookie, *errs.StatusError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RedirectHandler", ctx, details)
	ret0, _ := ret[0].(*http.Cookie)
	ret1, _ := ret[1].(*errs.StatusError)
	return ret0, ret1
}

// RedirectHandler indicates an expected call of RedirectHandler.
func (mr *MockValidatorMockRecorder) RedirectHandler(ctx, details any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RedirectHandler", reflect.TypeOf((*MockValidator)(nil).RedirectHandler), ctx, details)
}

// ValidateCookies mocks base method.
func (m *MockValidator) ValidateCookies(ctx context.Context, details requests.RequestDetails) (oauthmngr.Result, *errs.StatusError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateCookies", ctx, details)
	ret0, _ := ret[0].(oauthmngr.Result)
	ret1, _ := ret[1].(*errs.StatusError)
	return ret0, ret1
}

// ValidateCookies indicates an expected call of ValidateCookies.
func (mr *MockValidatorMockRecorder) ValidateCookies(ctx, details any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateCookies", reflect.TypeOf((*MockValidator)(nil).ValidateCookies), ctx, details)
}
