// Code generated by MockGen. DO NOT EDIT.
// Source: internal/ctls/requests/requests.go
//
// Generated by this command:
//
//	mockgen -source=internal/ctls/requests/requests.go -destination=test/mocks/mock_requests/mock_requests.go -package=mock_requests
//

// Package mock_requests is a generated GoMock package.
package mock_requests

import (
	context "context"
	io "io"
	http "net/http"
	reflect "reflect"

	requests "github.com/llnl/wormhole-holepunch/internal/ctls/requests"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// GetHeaders mocks base method.
func (m *MockClient) GetHeaders(ctx context.Context, url string, headers map[string]string, cookies []*http.Cookie) (map[string]string, *requests.RequestFailedError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHeaders", ctx, url, headers, cookies)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(*requests.RequestFailedError)
	return ret0, ret1
}

// GetHeaders indicates an expected call of GetHeaders.
func (mr *MockClientMockRecorder) GetHeaders(ctx, url, headers, cookies any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHeaders", reflect.TypeOf((*MockClient)(nil).GetHeaders), ctx, url, headers, cookies)
}

// GetJSON mocks base method.
func (m *MockClient) GetJSON(ctx context.Context, url string, headers map[string]string, v any) *requests.RequestFailedError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJSON", ctx, url, headers, v)
	ret0, _ := ret[0].(*requests.RequestFailedError)
	return ret0
}

// GetJSON indicates an expected call of GetJSON.
func (mr *MockClientMockRecorder) GetJSON(ctx, url, headers, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJSON", reflect.TypeOf((*MockClient)(nil).GetJSON), ctx, url, headers, v)
}

// GetJSONCookies mocks base method.
func (m *MockClient) GetJSONCookies(ctx context.Context, url string, headers map[string]string, cookies []*http.Cookie, v any) *requests.RequestFailedError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJSONCookies", ctx, url, headers, cookies, v)
	ret0, _ := ret[0].(*requests.RequestFailedError)
	return ret0
}

// GetJSONCookies indicates an expected call of GetJSONCookies.
func (mr *MockClientMockRecorder) GetJSONCookies(ctx, url, headers, cookies, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJSONCookies", reflect.TypeOf((*MockClient)(nil).GetJSONCookies), ctx, url, headers, cookies, v)
}

// PostJSONBody mocks base method.
func (m *MockClient) PostJSONBody(ctx context.Context, url string, headers map[string]string, body io.Reader, v any) *requests.RequestFailedError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostJSONBody", ctx, url, headers, body, v)
	ret0, _ := ret[0].(*requests.RequestFailedError)
	return ret0
}

// PostJSONBody indicates an expected call of PostJSONBody.
func (mr *MockClientMockRecorder) PostJSONBody(ctx, url, headers, body, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostJSONBody", reflect.TypeOf((*MockClient)(nil).PostJSONBody), ctx, url, headers, body, v)
}

// MockhttpClient is a mock of httpClient interface.
type MockhttpClient struct {
	ctrl     *gomock.Controller
	recorder *MockhttpClientMockRecorder
	isgomock struct{}
}

// MockhttpClientMockRecorder is the mock recorder for MockhttpClient.
type MockhttpClientMockRecorder struct {
	mock *MockhttpClient
}

// NewMockhttpClient creates a new mock instance.
func NewMockhttpClient(ctrl *gomock.Controller) *MockhttpClient {
	mock := &MockhttpClient{ctrl: ctrl}
	mock.recorder = &MockhttpClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockhttpClient) EXPECT() *MockhttpClientMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockhttpClient) Do(req *http.Request) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", req)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockhttpClientMockRecorder) Do(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockhttpClient)(nil).Do), req)
}
