package token

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"strings"

	"github.com/llnl/wormhole-holepunch/internal/ctls/errs"
	"github.com/llnl/wormhole-holepunch/internal/ctls/keys"
	"github.com/llnl/wormhole-holepunch/internal/ctls/logs"
	"github.com/llnl/wormhole-holepunch/internal/ctls/requests"
	"github.com/llnl/wormhole-holepunch/internal/wormhole"
)

// exchangeResp represents the response structure for /token/jwt exchange.
type exchangeResp struct {
	JWT string `json:"jwt"`
}

// retrieveWAT extracts and validates the token from the request header. The initial
// TokenContext object is generated but no Payload can be established at this point.
func (i internal) retrieveWAT(
	req requests.RequestDetails,
) (wormhole.TokenContext, bool, *errs.StatusError) {
	reqToken := cleanHeaderVal(req.Headers[i.tokenSvcArgs.TokenHeader])
	if reqToken == "" {
		return wormhole.TokenContext{}, false, nil
	}

	err := i.validator.Var(reqToken, "reqToken")
	if err != nil {
		return wormhole.TokenContext{}, true, err
	}

	// We've already verified the rough structure of the token.
	split := strings.Split(reqToken, ".")

	return wormhole.TokenContext{
		WAT:     reqToken,
		TokenID: split[0],
	}, true, nil
}

// wormholeAccessTokenFlow (WAT) handles the token exchange and caching flow for a
// token generated by the Wormhole Token Service. The valid wormhole.TokenContext
// and Token Service minted Jump Token will be returned.
func (i internal) wormholeAccessTokenFlow(
	ctx context.Context,
	ll logs.Logger,
	reqToken, tokenID string,
) (wormhole.TokenPayload, string, *errs.StatusError) {
	ctx, endSpan := ll.StartSpan(ctx, "wormholeAccessTokenFlow")
	defer endSpan()

	ll.DebugCtx(ctx, "wormholeAccessTokenFlow initiated")

	key := keys.WormholeAccessToken(tokenID)

	cs, found, sErr := i.getCache(ctx, ll, key, reqToken)
	if sErr != nil {
		return wormhole.TokenPayload{}, "", sErr
	} else if found {
		return cs.Payload, cs.decryptedJumpToken, nil
	}

	resp, sErr := i.exchangeToken(ctx, ll, key, reqToken)
	if sErr != nil {
		return wormhole.TokenPayload{}, "", sErr
	}

	cs.decryptedJumpToken = resp.JWT
	cs.decryptedToken = reqToken

	cs.Payload, sErr = decodeTrustedJWT(resp.JWT)
	if sErr != nil {
		i.storeInvalidCache(ctx, ll, key)

		return wormhole.TokenPayload{}, "", sErr
	}

	// Provide a clear log indicating that a TokenID can be
	// associated with the request.
	ll.InfoCtx(ctx, "authenticated token: "+cs.Payload.TokenID)

	i.storeCache(ctx, ll, key, cs)

	return cs.Payload, cs.decryptedJumpToken, nil
}

// oauthFlow handles request authorization missing a traditional x-token based upon
// sessions cookies.
// nolint: funlen
func (i internal) oauthFlow(
	ctx context.Context,
	ll logs.Logger,
	details requests.RequestDetails,
) (wormhole.TokenPayload, string, *errs.StatusError) {
	ctx, endSpan := ll.StartSpan(ctx, "oauthFlow")
	defer endSpan()

	ll.InfoCtx(ctx, "oauthFlow initiated")

	res, sErr := i.oauthValid.ValidateCookies(ctx, details)
	if sErr != nil {
		return wormhole.TokenPayload{}, "", sErr
	}

	var cs cache

	accessToken := res.AccessToken
	key := keys.WormholeOauthSession(accessToken)

	cs, found, sErr := i.getCache(ctx, ll, key, accessToken)
	if sErr != nil {
		ll.InfoCtx(ctx, sErr.Error())

		// After reviewing this error we know the cache has been cleared, it is best to
		// redirect them to the start of the login flow.
		return wormhole.TokenPayload{}, "", i.oauthValid.NewAuthRedirectErr(details)
	} else if found {
		return cs.Payload, cs.decryptedJumpToken, nil
	}

	var resp exchangeResp

	reqErr := i.client.GetJSON(ctx, i.oauthExchangeURL,
		map[string]string{
			keys.Oauth2ProxyAccessTokenHeader: accessToken,
		}, &resp)
	if reqErr != nil {
		ll.WarnCtx(
			ctx,
			"failed oauth token exchange "+i.oauthExchangeURL,
			ll.StringArg("error", reqErr.Error()),
		)

		// It might be nice to differentiate between errors here? There maybe cases where we simply
		// want to redirect the user without simply rejecting the request. Future improvement
		// likely required after the Token Service support finalized.
		return wormhole.TokenPayload{}, "", errs.SimpleAuthErr(reqErr)
	}

	// Simply capture the payload + JWT in the cache. The remainder of the cache is utilized
	// for token management. Any sessions should be managed through distinct mechanisms
	// in the future once Holepunch owns the entire request session.
	cs.decryptedJumpToken = resp.JWT
	cs.decryptedToken = accessToken

	cs.Payload, sErr = decodeTrustedJWT(resp.JWT)
	if sErr != nil {
		return wormhole.TokenPayload{}, "", errs.SimpleInternalErr(sErr)
	}

	i.storeCache(ctx, ll, key, cs)

	return cs.Payload, resp.JWT, sErr
}

// exchangeToken performs the token exchange with the authentication service. If specific
// cases are met (401 from Token Service) the proposed ID is invalidated in the cache.
func (i internal) exchangeToken(
	ctx context.Context,
	ll logs.Logger,
	key, reqToken string,
) (exchangeResp, *errs.StatusError) {
	var resp exchangeResp

	reqErr := i.client.GetJSON(
		ctx,
		i.tokenExchangeURL,
		map[string]string{
			i.tokenSvcArgs.TokenHeader: reqToken,
		},
		&resp,
	)
	if reqErr != nil {
		if reqErr.StatusCode == http.StatusUnauthorized {
			i.storeInvalidCache(ctx, ll, key)
		}

		ll.DebugCtx(
			ctx,
			"failed request to token service",
			ll.StringArg("error", reqErr.Error()),
		)

		return resp, errs.SimpleAuthErr(reqErr)
	}

	return resp, nil
}

// parseCookies is a helper function to parse cookies from the "Cookie" header
// in the RequestDetails structure.
func (i internal) parseCookies(details requests.RequestDetails) []*http.Cookie {
	cookies := make([]*http.Cookie, 0)

	// Split the cookies in the "Cookie" header using "; ".
	for part := range strings.SplitSeq(details.Headers[keys.CookieHeader], "; ") {
		// Split the individual cookie into name=value pairs.
		if kv := strings.SplitN(part, "=", 2); len(kv) == 2 {
			// In this case the cookies are being added for an internal request
			// to the trusted token service.
			// nolint: gosec
			cookies = append(cookies, &http.Cookie{
				Name:  kv[0],
				Value: kv[1],
			})
		}
	}

	return cookies
}

//

// cleanHeaderVal cleans up the token string by removing the 'Bearer' prefix.
func cleanHeaderVal(s string) string {
	return strings.TrimSpace(strings.TrimPrefix(s, "Bearer"))
}

// decodeTrustedJWT should only be used with trusted JWTs from the token service.
// There is likely a future MR to the service to expand the response and potentially
// avoid this step completely.
func decodeTrustedJWT(jwt string) (wormhole.TokenPayload, *errs.StatusError) {
	payload := wormhole.TokenPayload{}

	parts := strings.Split(jwt, ".")
	if len(parts) != 3 {
		return payload, errs.SimpleInternalErr(errors.New("invalid JWT format"))
	}

	b, err := base64.RawURLEncoding.DecodeString(parts[1])
	if err != nil {
		return payload, errs.SimpleInternalErr(fmt.Errorf("failed to decode payload: %w", err))
	}

	if err := json.Unmarshal(b, &payload); err != nil {
		return payload, errs.SimpleInternalErr(err)
	}

	return payload, nil
}
