// Code generated by MockGen. DO NOT EDIT.
// Source: internal/wormhole/registry/router.go
//
// Generated by this command:
//
//	mockgen -source=internal/wormhole/registry/router.go -destination=test/mocks/mock_registry/mock_registry.go -package=mock_registry
//

// Package mock_registry is a generated GoMock package.
package mock_registry

import (
	context "context"
	reflect "reflect"

	errs "github.com/llnl/wormhole-holepunch/internal/ctls/errs"
	logs "github.com/llnl/wormhole-holepunch/internal/ctls/logs"
	requests "github.com/llnl/wormhole-holepunch/internal/ctls/requests"
	wormhole "github.com/llnl/wormhole-holepunch/internal/wormhole"
	registry "github.com/llnl/wormhole-holepunch/internal/wormhole/registry"
	jetstream "github.com/nats-io/nats.go/jetstream"
	gomock "go.uber.org/mock/gomock"
)

// MockRouter is a mock of Router interface.
type MockRouter struct {
	ctrl     *gomock.Controller
	recorder *MockRouterMockRecorder
	isgomock struct{}
}

// MockRouterMockRecorder is the mock recorder for MockRouter.
type MockRouterMockRecorder struct {
	mock *MockRouter
}

// NewMockRouter creates a new mock instance.
func NewMockRouter(ctrl *gomock.Controller) *MockRouter {
	mock := &MockRouter{ctrl: ctrl}
	mock.recorder = &MockRouterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRouter) EXPECT() *MockRouterMockRecorder {
	return m.recorder
}

// AsyncFetchSources mocks base method.
func (m *MockRouter) AsyncFetchSources() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AsyncFetchSources")
}

// AsyncFetchSources indicates an expected call of AsyncFetchSources.
func (mr *MockRouterMockRecorder) AsyncFetchSources() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AsyncFetchSources", reflect.TypeOf((*MockRouter)(nil).AsyncFetchSources))
}

// AuthorizeProxy mocks base method.
func (m *MockRouter) AuthorizeProxy(ctx context.Context, ll logs.Logger, req requests.RequestDetails, up wormhole.TokenContext) *errs.StatusError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthorizeProxy", ctx, ll, req, up)
	ret0, _ := ret[0].(*errs.StatusError)
	return ret0
}

// AuthorizeProxy indicates an expected call of AuthorizeProxy.
func (mr *MockRouterMockRecorder) AuthorizeProxy(ctx, ll, req, up any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthorizeProxy", reflect.TypeOf((*MockRouter)(nil).AuthorizeProxy), ctx, ll, req, up)
}

// FetchProxyControls mocks base method.
func (m *MockRouter) FetchProxyControls() map[string]registry.ProxyControls {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchProxyControls")
	ret0, _ := ret[0].(map[string]registry.ProxyControls)
	return ret0
}

// FetchProxyControls indicates an expected call of FetchProxyControls.
func (mr *MockRouterMockRecorder) FetchProxyControls() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchProxyControls", reflect.TypeOf((*MockRouter)(nil).FetchProxyControls))
}

// PublishSources mocks base method.
func (m *MockRouter) PublishSources(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishSources", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishSources indicates an expected call of PublishSources.
func (mr *MockRouterMockRecorder) PublishSources(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishSources", reflect.TypeOf((*MockRouter)(nil).PublishSources), ctx)
}

// RefreshControls mocks base method.
func (m *MockRouter) RefreshControls(msg jetstream.Msg) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RefreshControls", msg)
}

// RefreshControls indicates an expected call of RefreshControls.
func (mr *MockRouterMockRecorder) RefreshControls(msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshControls", reflect.TypeOf((*MockRouter)(nil).RefreshControls), msg)
}

// ReportControlsJSON mocks base method.
func (m *MockRouter) ReportControlsJSON() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReportControlsJSON")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// ReportControlsJSON indicates an expected call of ReportControlsJSON.
func (mr *MockRouterMockRecorder) ReportControlsJSON() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportControlsJSON", reflect.TypeOf((*MockRouter)(nil).ReportControlsJSON))
}

// SubscribeToSources mocks base method.
func (m *MockRouter) SubscribeToSources(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeToSources", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubscribeToSources indicates an expected call of SubscribeToSources.
func (mr *MockRouterMockRecorder) SubscribeToSources(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeToSources", reflect.TypeOf((*MockRouter)(nil).SubscribeToSources), ctx)
}
